
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-m23/team02-m23-9am-3
owner: ucsb-cs156-m23
repo_name: team02-m23-9am-3
pull_requests: [{"author":{"id":"U_kgDOBXuuuQ","is_bot":false,"login":"Danny-You","name":""},"headRefName":"Danny-ArticlesTable-Controller","number":57,"title":"Danny articles table controller","url":"https://github.com/ucsb-cs156-m23/team02-m23-9am-3/pull/57"},{"author":{"id":"MDQ6VXNlcjcyODI4OTQ1","is_bot":false,"login":"LolExile","name":"Johnny Wang "},"headRefName":"Johnny-HelpRequestTable","number":56,"title":"HelpRequest Table included","url":"https://github.com/ucsb-cs156-m23/team02-m23-9am-3/pull/56"},{"author":{"id":"MDQ6VXNlcjYyMzY5NTUy","is_bot":false,"login":"InariHimeko","name":""},"headRefName":"Wenxuan-RecRequestController","number":55,"title":"Wenxuan add RecRequestController","url":"https://github.com/ucsb-cs156-m23/team02-m23-9am-3/pull/55"},{"author":{"id":"U_kgDOBtnu_g","is_bot":false,"login":"Kanagawa-okiNamiUra","name":""},"headRefName":"Albert-UCSB_Dining_Commons_Menu_Controller","number":54,"title":"AW--ucsb dining commons menu items controller","url":"https://github.com/ucsb-cs156-m23/team02-m23-9am-3/pull/54"},{"author":{"id":"U_kgDOBtnu_g","is_bot":false,"login":"Kanagawa-okiNamiUra","name":""},"headRefName":"Albert-UCSB_Dining_Commons_Menu_DTB","number":53,"title":"setup dt for UCSBDiningCommonsMenuItem","url":"https://github.com/ucsb-cs156-m23/team02-m23-9am-3/pull/53"},{"author":{"id":"U_kgDOBXuuuQ","is_bot":false,"login":"Danny-You","name":""},"headRefName":"Danny-ArticlesTable","number":51,"title":"dy - Added entity and repository files for Articles","url":"https://github.com/ucsb-cs156-m23/team02-m23-9am-3/pull/51"}]
