
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-m23/team02-m23-9am-3
owner: ucsb-cs156-m23
repo_name: team02-m23-9am-3
pull_requests: [{"author":{"id":"MDQ6VXNlcjExMTkwMTc=","is_bot":false,"login":"pconrad","name":"Phill Conrad"},"headRefName":"pc-fix-workflows-02-and-04","number":50,"title":"Pc fix workflows 02 and 04","url":"https://github.com/ucsb-cs156-m23/team02-m23-9am-3/pull/50"},{"author":{"id":"U_kgDOBXznew","is_bot":false,"login":"lawrencewang30","name":""},"headRefName":"Lawrence-UCSBOrganization-Controller","number":49,"title":"Added UCSB Organization Controller and all issues implemented","url":"https://github.com/ucsb-cs156-m23/team02-m23-9am-3/pull/49"},{"author":{"id":"U_kgDOBXznew","is_bot":false,"login":"lawrencewang30","name":""},"headRefName":"Lawrence-UCSBOrganization-Database","number":47,"title":"Added Entity and Repository files to UCSB Organization","url":"https://github.com/ucsb-cs156-m23/team02-m23-9am-3/pull/47"}]
